LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := VLC
LOCAL_SRC_FILES := org.videolan.vlc_13021208.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PREBUILT_JNI_LIBS := libc++_shared.so libmla.so libvlcjni.so libvlc.so
LOCAL_MODULE_TARGET_ARCH := x86_64
include $(BUILD_PREBUILT)
