LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := KeePassDX
LOCAL_SRC_FILES := com.kunzisoft.keepass.libre_35.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PREBUILT_JNI_LIBS := libargon2.so libfinal-key.so
LOCAL_MODULE_TARGET_ARCH := x86_64
include $(BUILD_PREBUILT)
