LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Telegram
LOCAL_SRC_FILES := org.telegram.messenger_19889.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_PREBUILT_JNI_LIBS := libtgvoip1.1.so libtgvoip3.1.so libtmessages.30.so
LOCAL_MODULE_TARGET_ARCH := x86_64
include $(BUILD_PREBUILT)
